### ISSUE TITLE
Configure Proxy in Flogo

### ISSUE THREAD

**Issue by akpuvvada** [retgits/flogo-components#16]
When I try to Build Flogo Apps from UI, I am getting failed message and when I check logs for the Flogo container, I am seeing error indicating that Flogo is not able to connect to git.
I have Proxy configured on Docker settings.
Any idea how to configure Proxy on Flogo?

**Comment by retgits** [comment]
Hi, this is a question for the Flogo team. I'll close the issue here as I see you created an issue in their repo too https://github.com/TIBCOSoftware/flogo/issues/514
