### ISSUE TITLE
Install Missing Components

### ISSUE THREAD

**Issue by mshahat** [retgits/flogo-components#2]
Hello, 

Probably reference to how to install missing components in case wanting to modify under flogo ui

Thanks, 

<img width="534" alt="screen shot 2018-03-06 at 17 53 11" src="https://user-images.githubusercontent.com/8035442/37048974-569964d4-2167-11e8-8d36-75f1bbed3c7d.png">

**Comment by retgits** [comment]
Hi! Unfortunately, this is a current limitation in Flogo Web that it doesn't automatically import activities you do not have installed yet. To workaround this you can open an existing flow (or create a new flow) and import the activities using the "Install new activity" button. 

Having said that, good idea to add a section how to do that 😄

**Comment by retgits** [comment]
Updated with https://github.com/retgits/flogo-components/commit/1e2a4a9e3aacd76113d17ffbf10fc566a0dec957 and https://github.com/retgits/flogo-components/commit/27238310825be834c71c92e86832d14b02e127e6 to cover the installation (including URLs to activities you'll need to import)
